@startuml
'https://plantuml.com/sequence-diagram

title Example of a Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":xxxxView" as System
participant ":xxxxController" as Ctrl
participant ":Class1" as C1

activate User

User -> System: Authentication request
System -> Ctrl: authenticate(userId, pwd)
Ctrl -> C1: doLogIn(userId, pwd)
C1 --> Ctrl: userToken
Ctrl --> System: ok
System --> User: Authentication response

@enduml