@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Want to get the book details by isbn as Librarian or Reader

actor "Librarian or Reader" as User
participant "Ctrl:booksController" as Ctrl
participant "service:booksService" as Service
participant "repo:booksRepository" as Repo
activate User

User -> Ctrl: Request book details
activate Ctrl
Ctrl -> Service: FindByIsbn(Isbn)
activate Service
Service -> Repo: findByIsbn(Isbn)
activate Repo

Repo --> Service: bookDetails
deactivate Repo
Service --> Ctrl: bookDetails
deactivate Service
Ctrl --> User: bookDetails
deactivate Ctrl

@enduml
