@startuml

autonumber

title Create Generic Resource (POST)

participant "GenericController" as Controller
participant "GenericService" as Service
participant "GenericMapper" as Mapper
participant "GenericRepository" as Repo
participant "GenericDataSchema" as DataSchema
database "SQL DataBase" as MYSQL
database "Mongo DataBase" as MONGO
database "Redis Cache" as REDIS

-> Controller: POST /api/generic
activate Controller

    Controller -> Service: map DTO to entity
    activate Service

        Service -> Mapper: map DTO to entity
        activate Mapper

            Mapper --> Service: mapped entity
        deactivate Mapper

        Service -> Repo: save(entity)
        activate Repo

            Repo -> DataSchema: maps to DataSchema
            activate DataSchema

                DataSchema --> Repo: return dataSchema object
            deactivate DataSchema

            alt Persistence = MySQL

            Repo -> MYSQL: INSERT INTO generic VALUES (...)
            activate MYSQL

                MYSQL --> Repo: created data
            deactivate MYSQL

            else Persistence = MongoDB

            Repo -> MONGO: save({...})
            activate MONGO

                MONGO --> Repo: created data
            deactivate MONGO

            end

            Repo -> REDIS: add cache entry for id
            activate REDIS

                REDIS --> Repo: cache saving result
            deactivate REDIS

            Repo -> DataSchema: maps to Domain
            activate DataSchema

                DataSchema --> Repo: return domain list
            deactivate DataSchema

            Repo --> Service: returns saved entity
        deactivate Repo

        Service -> Mapper: map to DTO
        activate Mapper

            Mapper --> Service: returns DTO
        deactivate Mapper

        Service --> Controller: returns DTO
    deactivate Service

<-- Controller: returns created data (DTO)
deactivate Controller

@enduml