pipeline {
    agent any

    parameters {
        string(
            name: 'BRANCH',
            defaultValue: 'dev'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out Genres Service...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('genres') {
                    echo 'Validating...'
                    sh 'mvn validate'

                    echo 'Building...'
                    sh 'mvn clean compile'

                    echo 'Static Code Analysis...'
                    sh 'mvn -B spotbugs:spotbugs spotbugs:check -DskipTests'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site',
                        reportFiles: 'spotbugs.html',
                        reportName: 'SpotBugs Report'
                    ])
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('genres') {
                    echo 'Unit Testing...'
                    sh 'mvn test'

                    echo 'Mutation Testing...'
                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'

                    echo 'Reporting Results...'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/pit-reports',
                        reportFiles: '**/index.html',
                        reportName: 'PITest Mutation Report'
                    ])
                }
            }
        }

        stage ('Integration Test') {
            steps {
                dir('genres') {
                    echo 'Integration Testing...'
                    sh 'mvn verify -DskipUnitTests'

                    echo 'Code Coverage...'
                    sh 'mvn jacoco:report'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Package') {
            steps {
                dir('genres') {
                    echo 'Packaging...'
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage ('Containerize') {
            steps {
                dir('genres') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t miguel04cardoso/genres-service:latest .'
                }
            }
        }

        stage('Push to Docker Registry') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
              sh 'docker login -u $USER -p $PASS'
              sh 'docker push miguel04cardoso/genres-service:latest'
            }
          }
        }

        stage('Smoke Test - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                script {
                    retry(3) {
                        sleep 5
                        sh '''
                          curl -f http://143.47.57.150:4677/genres/actuator/health
                        '''
                    }
                }
            }
        }

        stage('Health Check - Production') {
            when {
                expression { params.BRANCH == 'prod' }
            }
            steps {
                script {
                    try {
                        retry(3) {
                            sleep 5
                            sh 'curl -fsS http://143.47.57.150:4677/genres/actuator/health'
                        }
                    } catch (e) {
                        sh 'docker service rollback library-management-system_genres-service'
                        error("Health Check Failed -> Rolled Back")
                    }
                }
            }
        }
    }
}