version: "3.8"

networks:
  traefik-public:
    external: true

services:
  traefik:
    image: traefik:2
    command:
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:4677"
      - "--api.insecure=true"
    ports:
      - "4677:4677"
      - "8888:8080"
    networks:
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq.rule=PathPrefix(`/rabbitmq`)"
        - "traefik.http.routers.rabbitmq.entrypoints=web"
        - "traefik.http.middlewares.rabbitmq-strip.stripprefix.prefixes=/rabbitmq"
        - "traefik.http.routers.rabbitmq.middlewares=rabbitmq-strip"
        - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"