pipeline {
    agent any

    parameters {
        string(
            name: 'BRANCH',
            defaultValue: 'dev'
        )
    }

    environment {
        PACT_BROKER_URL = 'https://isep-fd4645c7.pactflow.io'
        VERSION = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out Books Service...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('books') {
                    echo 'Validating...'
                    sh 'mvn validate'

                    echo 'Building...'
                    sh 'mvn clean compile'

                    echo 'Static Code Analysis...'
                    sh 'mvn -B spotbugs:spotbugs spotbugs:check -DskipTests'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site',
                        reportFiles: 'spotbugs.html',
                        reportName: 'SpotBugs Report'
                    ])
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('books') {
                    echo 'Unit Testing...'
                    sh 'mvn test'

                    echo 'Mutation Testing...'
                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'

                    echo 'Reporting Results...'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/pit-reports',
                        reportFiles: '**/index.html',
                        reportName: 'PITest Mutation Report'
                    ])
                }
            }
        }

        stage('Integration Test') {
            steps {
                dir('books') {
                    echo 'Integration Testing...'
                    sh 'mvn verify -DskipUnitTests'

                    echo 'Code Coverage...'
                    sh 'mvn jacoco:report'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Publish Pact') {
            steps {
                dir('books') {
                    echo 'Publishing Pact...'
                    withCredentials([string(credentialsId: 'pact-broker-token',variable: 'PACT_BROKER_TOKEN')]) {
                        sh """
                          mvn pact:publish \
                            -Dpact.broker.url=${PACT_BROKER_URL} \
                            -Dpact.broker.token=$PACT_BROKER_TOKEN \
                            -Dpact.consumer.version=${VERSION}
                        """
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('books') {
                    echo 'Packaging...'
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage ('Containerize') {
            steps {
                dir('books') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t miguel04cardoso/books-service:latest .'
                }
            }
        }

        stage('Push to Docker Registry') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
              sh 'docker login -u $USER -p $PASS'
              sh 'docker push miguel04cardoso/books-service:latest'
            }
          }
        }

        stage('Deploy - Books Service') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                dir('books') {
                    script {
                        def composeFile = 'docker-compose.yml'
                        def stackName = 'books'

                        if (params.BRANCH == 'prod') {
                            composeFile = 'docker-compose-prod.yml'
                        }

                        sh """
                            docker stack deploy -c ${composeFile} ${stackName}
                        """
                    }
                }
            }
        }

        stage('Smoke Test - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                dir('books/load-tests') {
                    echo 'Running Smoke Test...'
                    sh '''
                        docker run --rm -i -v $PWD:/k6 grafana/k6 run /k6/smoke-test.js
                    '''
                }
            }
        }

        stage('Performance Tests - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                dir('books/load-tests') {
                    echo 'Running Performance Tests...'
                    sh '''
                        chmod 777 .
                        docker run --rm -i -v $PWD:/k6 grafana/k6 run /k6/k6-books.js --summary-export=/k6/k6-summary.json
                    '''
                }
            }
        }

        stage('Auto Scale - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                dir('books/load-tests') {
                    echo 'Scaling Books Service Based On Load Test Results...'
                    sh '''
                        chmod +x scale-books.sh
                        ./scale-books.sh
                    '''
                }
            }
        }

        stage('Health Check - Production') {
            when {
                expression { params.BRANCH == 'prod' }
            }
            steps {
                script {
                    try {
                        retry(3) {
                            sleep 5
                            sh 'curl -fsS http://143.47.57.150:4677/books/actuator/health'
                        }
                    } catch (e) {
                        sh 'docker service rollback library-management-system_books-service'
                        error("Health Check Failed -> Rolled Back")
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Cleaning Old Docker Images...'
            sh '''
                docker image prune -a -f --filter "label=service=books" --filter "until=48h"
            '''
        }
    }
}