@startuml

autonumber

title Get Generic Resource by ID

actor "User" as USER
participant ":System" as System

activate USER

    USER -> System: /GET /api/generic/{id}
    activate System

        System --> USER: returns requested data
    deactivate System

deactivate USER

@enduml
