@startuml

autonumber

title Delete Generic Resource

actor "User" as USER
participant ":System" as System

activate USER

    USER -> System: /DELETE /api/generic/{id}
    activate System

        System --> USER: informs operation success
    deactivate System

deactivate USER

@enduml
