pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out Readers Service...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('readers') {
                    echo 'Validating...'
                    sh 'mvn validate'

                    echo 'Building...'
                    sh 'mvn clean compile'

                    echo 'Static Code Analysis...'
                    sh 'mvn -B spotbugs:spotbugs spotbugs:check -DskipTests'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site',
                        reportFiles: 'spotbugs.html',
                        reportName: 'SpotBugs Report'
                    ])
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('readers') {
                    echo 'Unit Testing...'
                    sh 'mvn test'

                    echo 'Mutation Testing...'
                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'

                    echo 'Reporting Results...'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/pit-reports',
                        reportFiles: '**/index.html',
                        reportName: 'PITest Mutation Report'
                    ])
                }
            }
        }

        stage ('Integration Test') {
            steps {
                dir('readers') {
                    echo 'Integration Testing...'
                    sh 'mvn verify -DskipUnitTests'

                    echo 'Code Coverage...'
                    sh 'mvn jacoco:report'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Package') {
            steps {
                dir('readers') {
                    echo 'Packaging...'
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage ('Containerize') {
            steps {
                dir('readers') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t miguel04cardoso/readers-service:latest .'
                    sh 'docker tag miguel04cardoso/readers-service:latest miguel04cardoso/readers-service:canary'
                }
            }
        }

        stage('Push to Docker Registry') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
              sh 'docker login -u $USER -p $PASS'
              sh 'docker push ${DOCKER_USER}/readers-service:latest'
              sh 'docker push ${DOCKER_USER}/readers-service:canary'
            }
          }
        }
    }
}