pipeline {
    agent any

    parameters {
        string(
            name: 'BRANCH',
            defaultValue: 'dev'
        )
    }

    environment {
        PACT_BROKER_URL = 'https://isep-fd4645c7.pactflow.io'
        VERSION = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out Readers Service...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('readers') {
                    echo 'Validating...'
                    sh 'mvn validate'

                    echo 'Building...'
                    sh 'mvn clean compile'

                    echo 'Static Code Analysis...'
                    sh 'mvn -B spotbugs:spotbugs spotbugs:check -DskipTests'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site',
                        reportFiles: 'spotbugs.html',
                        reportName: 'SpotBugs Report'
                    ])
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('readers') {
                    echo 'Unit Testing...'
                    sh 'mvn test'

                    echo 'Mutation Testing...'
                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'

                    echo 'Reporting Results...'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/pit-reports',
                        reportFiles: '**/index.html',
                        reportName: 'PITest Mutation Report'
                    ])
                }
            }
        }

        stage('Integration Test') {
            steps {
                dir('readers') {
                    echo 'Integration Testing...'
                    sh 'mvn verify -DskipUnitTests'

                    echo 'Code Coverage...'
                    sh 'mvn jacoco:report'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Publish Pact') {
            steps {
                dir('books') {
                    echo 'Publishing Pact...'
                    withCredentials([string(credentialsId: 'pact-broker-token',variable: 'PACT_BROKER_TOKEN')]) {
                        sh """
                          mvn pact:publish \
                            -Dpact.broker.url=${PACT_BROKER_URL} \
                            -Dpact.broker.token=$PACT_BROKER_TOKEN \
                            -Dpact.consumer.version=${VERSION} \
                            -Dpact.git.branch=${params.BRANCH}
                        """
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('readers') {
                    echo 'Packaging...'
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage ('Containerize') {
            steps {
                dir('readers') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t miguel04cardoso/readers-service:latest .'
                    sh 'docker tag miguel04cardoso/readers-service:latest miguel04cardoso/readers-service:canary'
                }
            }
        }

        stage('Push to Docker Registry') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
              sh 'docker login -u $USER -p $PASS'
              sh 'docker push miguel04cardoso/readers-service:canary'
            }
          }
        }

        stage('Deploy - Readers Service') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                dir('readers') {
                    script {
                        def composeFile = 'docker-compose.yml'
                        def stackName = 'readers'

                        if (params.BRANCH == 'prod') {
                            composeFile = 'docker-compose-prod.yml'
                        }

                        sh """
                            docker stack deploy -c ${composeFile} ${stackName}
                        """
                    }
                }
            }
        }

        stage('Smoke Test - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                script {
                    try {
                        retry(3) {
                            sleep 5
                            sh '''
                              curl -f http://143.47.57.150:4677/readers/actuator/health
                            '''
                        }
                    } catch (e) {
                        sh '''
                          chmod +x rollout-canary.sh
                          ./cancel-update.sh
                        '''
                        error("Smoke Test Failed -> Rolled Back")
                    }
                }
            }
        }

        stage('Canary Rollout - Staging') {
            when {
                expression { params.BRANCH == 'staging' }
            }
            steps {
                script {
                     sh '''
                         chmod +x rollout-canary.sh
                         ./rollout-canary.sh
                     '''
                }
            }
        }

        stage('Health Check - Production') {
            when {
                expression { params.BRANCH == 'prod' }
            }
            steps {
                script {
                    try {
                        retry(3) {
                            sleep 5
                            sh 'curl -fsS http://143.47.57.150:4677/readers/actuator/health'
                        }
                    } catch (e) {
                        sh 'docker service rollback library-management-system_readers-service'
                        error("Health Check Failed -> Rolled Back")
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Cleaning Old Docker Images...'
            sh '''
                docker image prune -a -f --filter "label=service=readers" --filter "until=48h"
            '''
        }
    }
}