@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
hide circle
class Authors <<entity>>{
    - Name : String
    - Short Bio : String
    - AuthorId : int
    - Photo : ??
}

class AuthorsController {
    +createAuthor(name, short bio): void
    +saveCreatedAuthor(): Result
    +UpdateAuthors(short bio): data
}

class AuthorsServiceImpl implements AuthorsService{
}

interface AuthorsService {
    + create(name, short bio) : Authors
    + findByName(AuthorsName)
    + findById(AuthorsData)
    + update(AuthorsData)
}

interface AuthorsRepository {
    + create(name, short bio) : Authors
    + update(AuthorsData)
}

AuthorsServiceImpl ..> Authors
AuthorsController ..> AuthorsService
AuthorsServiceImpl .left.> AuthorsRepository
@enduml
