spring.application.name=LMS-Books

## Profiles - bootstrap
spring.profiles.active=bootstrap

## JWT
jwt.private.key=classpath:rsa.private.key
jwt.public.key=classpath:rsa.public.key

## Swagger UI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

## Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

## Feature Flags
feature.bookPhotoDelete.enabled=${FEATURE_BOOK_PHOTO_DELETE_ENABLED:true}

## Hibernate Settings
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

## RabbitMQ
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

## Multipart File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
file.photo_max_size=20000
file.upload-dir=uploads