@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET book details by Isbn as librarian

actor "Librarian" as User
participant ":Rest" as Rest
participant "Ctrl:ReaderController" as Ctrl
participant "service:ReaderService" as Service
participant "repo:ReaderRepository" as Repo

activate User

User -> Rest: requests the top 5 readers per genre in a certain time

Rest -> Ctrl: Top5ByGenre(genre);

Ctrl -> Service: getTop5(ReaderDTO)
Service -> Repo: getTop5(book)
Repo --> Service: book or error
Service --> Ctrl: book or error
Ctrl --> Rest: book or error
Rest --> User: get top 5 books

@enduml
