@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Register a new book as librarian

actor "Librarian" as User
participant ":Rest" as Rest
participant "Ctrl:BookController" as Ctrl
participant "service:BookService" as Service
participant "repo:AuthorsRepository" as RepoAuthors
participant "repo:GenreRepository" as RepoGenre
participant "repo:BookRepository" as Repo
participant "book:Book" as Book


activate User

User -> Rest: requests to create on given data

Rest -> Ctrl: createBook(requestBody);

Ctrl -> Service: registerBook(ISBN,title, genre, description, author(s))
Service -> RepoAuthors: getAuthors(authors)
RepoAuthors --> Service: authors or error
Service -> RepoGenre: getGenre(genre)
RepoGenre --> Service: genre or error
Service -> Book: Book(isbn, title, genre, description, author(s))
Service -> Repo: create(book)
Repo --> Service: book or error
Service --> Ctrl: book or error
Ctrl --> Rest: book or error
Rest --> User: updated book or error

@enduml
