@startuml

autonumber

title Post Generic Resource

actor "User" as USER
participant "BackEnd" as System
database "SQL DataBase" as MYSQL
database "SQL DataBase" as MYSQL
database "Mongo DataBase" as MONGO
database "Redis Cache" as REDIS

activate USER

    USER -> System: /POST /api/generic
    activate System

        alt Persistence = MySQL

            System -> MYSQL: INSERT INTO generic VALUES (...)
            activate MYSQL

                MYSQL --> System: created data
            deactivate MYSQL

        else Persistence = MongoDB

            System -> MONGO: save({...})
            activate MONGO

                MONGO --> System: created data
            deactivate MONGO

        end

        System -> REDIS: add cache entry for id
        activate REDIS

            REDIS --> System: cache saving result
        deactivate REDIS

        System --> USER: returns created resource
    deactivate System

deactivate USER

@enduml
