pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out Auth-Users Service...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('auth-users') {
                    echo 'Validating...'
                    sh 'mvn validate'

                    echo 'Building...'
                    sh 'mvn clean compile'

                    echo 'Static Code Analysis...'
                    sh 'mvn -B spotbugs:spotbugs spotbugs:check -DskipTests'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site',
                        reportFiles: 'spotbugs.html',
                        reportName: 'SpotBugs Report'
                    ])
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('auth-users') {
                    echo 'Unit Testing...'
                    sh 'mvn test'

                    echo 'Mutation Testing...'
                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'

                    echo 'Reporting Results...'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/pit-reports',
                        reportFiles: '**/index.html',
                        reportName: 'PITest Mutation Report'
                    ])
                }
            }
        }

        stage ('Integration Test') {
            steps {
                dir('auth-users') {
                    echo 'Integration Testing...'
                    sh 'mvn verify -DskipUnitTests'

                    echo 'Code Coverage...'
                    sh 'mvn jacoco:report'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                    ])
                }
            }
        }

        stage('Package') {
            steps {
                dir('auth-users') {
                    echo 'Packaging...'
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage ('Containerize') {
            steps {
                dir('auth-users') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t miguel04cardoso/auth-users-service:latest .'
                }
            }
        }
    }
}
