@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET book details by Isbn as librarian

actor "Librarian" as User
participant ":Rest" as Rest
participant "Ctrl:GenreController" as Ctrl
participant "service:GenreService" as Service
participant "repo:GenreRepository" as Repo

activate User

User -> Rest: requests the top 5 genres by books

Rest -> Ctrl: Top5();

Ctrl -> Service: getTop5(GenreDTO)
Service -> Repo: getTop5(genre)
Repo --> Service: genre or error
Service --> Ctrl: genre or error
Ctrl --> Rest: genre or error
Rest --> User: get top 5 genre

@enduml
