@startuml

skinparam classAttributeIconSize 0
hide circle
hide methods

class isbn{
    - isbn: string
}

class title{
    - title: string
}

class genre{
    - genre: string
}

class description{
    - description: string
}

class authors{
    - authors: string[]
}

class Book {
    - isbn: isbn
    - title: title
    - genre: genre
    - description: description
    - authors: authors
}
@enduml
