@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    - password
}

class Username{
    - username
}

class Librarian extends User{
}

class ISBN{
/'temos que implementar alguma validação?'/
/'https://en.wikipedia.org/wiki/ISBN'/
    - isbn: string
}

class Title{
/'regras?'/
    - title: string
}

class Genre{
/'escolhido de uma lista?'/
    - genre: string
}

class Description{
/'limite de caractéres?'/
    - description: string
}

class Book {
}

class Author {
    - author number
    - name
    - photo
    - short bio
    /'perguntar '/
   }

class Reader extends User{
    - name /'regras?'/
    - birthDate /'limite inferior/superior? '/
    - gdprConsent /'que implicações tem?'/
}

class ReaderNumber {
}

class Lending {
    - startDate
    - limitDate
    - returnDate
    - returned
}

class Fine {
}

class PhoneNr {
/'como fazer a validação?'/
    - number
}

class Email {
    /'perguntar se o domínio tem que ser validado?'/
    /'há domínios restritos?'/
    - user
    - domain
}

class Name {
    - name : String
}

Librarian "1" -- "0..*" Author : registers/updates >
Librarian "1" -- "0..*" Book : registers/updates >
Book "1..*" -up- "1..*"  Author
Reader "1" -- "1*" PhoneNr  /'mais que um?'/
Reader "1" -- "1*" Email   /'mais que um?'/
ReaderNumber "1" -o Lending
Reader "1" *- ReaderNumber
Lending "1" o-up- "0..*" ISBN
Book "1" *- "1" ISBN
Book "1" *-left- "1" Title
Book  "1" o-- "1..*"  Genre
Book  "1" *-- "1"  Description
Lending "1" *-- "0..1" Fine
Reader "1" *- "1" Name
Author "1" *-down- "1" Name
User "1" *- "1" Username

@enduml

