@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title Register a new reader as anonymous

actor "Anonymous" as User
participant ":System" as System
participant "Ctrl:ReaderController" as Ctrl
participant "service:ReaderService" as Service
participant "repo:ReaderRepository" as Repo
participant "reader:Reader" as Reader

activate User

User -> System: requests reader registration based on given data

System -> Ctrl: registerReader(RegisterReaderRequest);

Ctrl -> Service: create(name, dateOfBirth, ...)
Service -> Reader: Reader(name, dateOfBirth, ...)
Service -> Repo: add(reader)
Repo --> Service: reader or error
Service --> Ctrl: reader or error
Ctrl --> System: reader or error
System --> User: registered reader or error

@enduml
